apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: lion-88
  name: lion-88
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: lion-88
status:
  loadBalancer: {}
